language: go

go:
  - 1.4.2
  - tip

addons:
  postgresql: "9.4"
  apt:
    packages:
      - python3

before_script:
  - psql -c 'create database tinfoilhat_test;' -U postgres

script:
  - go list ./... | while read pkg; do go test -v ${pkg} || return 1; done
