# tinfoilhat.toml: config file for tinfoilhat
# Please check all values before running tinfoilhat.

log_file = "/tmp/tinfoilhat.log"

checker_timeout = "11s"

[Database]
connection = "user=postgres dbname=tinfoilhat sslmode=disable"
max_connections = 90 # should be less than same value in postgresql.conf

[Scoreboard]
www_path = "/home/mikhail/dev/tin_foil_hat/src/tinfoilhat/scoreboard/www"
addr = ":8000"
update_timeout = "1s"

[Pulse]
start = "Aug 2 15:04 2015"
half = "4h"
lunch = "1h"
round_len = "2m"
check_timeout = "30s"
darkest_time = "1h"

[FlagReceiver]
addr = ":8080"
receive_timeout = "1s"
socket_timeout = "10s"

[AdvisoryReceiver]
addr = ":8090"
receive_timeout = "30s"
socket_timeout = "1m"

[[Teams]]
name = "FooTeam"
subnet = "10.0.1.0/24"
vulnbox = "10.0.1.3"

[[Teams]]
name = "BarTeam"
subnet = "10.0.2.0/24"
vulnbox = "10.0.2.3"

[[Services]]
name = "FooService"
port = 53000
checker_path = "/path/too/foo_checker.py"

[[Services]]
name = "BarService"
port = 63000
checker_path = "/path/too/bar_checker.py"

[[Services]]
name = "UdpService"
port = 43000
checker_path = "/path/too/bar_checker.py"
udp = true
